// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:VisualStudio.SpellChecker.Common.CommonUtilities.ToRegexes(System.String)~System.Collections.Generic.IEnumerable{System.Text.RegularExpressions.Regex}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:VisualStudio.SpellChecker.Common.CommonUtilities.LoadUserDictionary(System.String,System.Boolean,System.Boolean)~System.Collections.Generic.IEnumerable{System.String}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:VisualStudio.SpellChecker.Common.CommonUtilities.SaveCustomDictionary(System.String,System.Boolean,System.Boolean,System.Collections.Generic.IEnumerable{System.String})")]
[assembly: SuppressMessage("Design", "CA1032:Implement standard exception constructors", Justification = "<Pending>", Scope = "type", Target = "~T:GlobExpressions.GlobPatternException")]
[assembly: SuppressMessage("Naming", "CA1711:Identifiers should not have incorrect suffix", Justification = "<Pending>", Scope = "type", Target = "~T:VisualStudio.SpellChecker.Common.Configuration.SpellCheckerDictionary")]
[assembly: SuppressMessage("Design", "CA1002:Do not expose generic lists", Justification = "<Pending>", Scope = "member", Target = "~P:VisualStudio.SpellChecker.Common.Configuration.Legacy.SpellCheckerLegacyConfiguration.DictionaryLanguages")]
[assembly: SuppressMessage("Design", "CA1002:Do not expose generic lists", Justification = "<Pending>", Scope = "member", Target = "~P:VisualStudio.SpellChecker.Common.Configuration.Legacy.SpellCheckerLegacyConfiguration.IgnoredFilePatterns")]
[assembly: SuppressMessage("Design", "CA1002:Do not expose generic lists", Justification = "<Pending>", Scope = "member", Target = "~P:VisualStudio.SpellChecker.Common.Configuration.Legacy.SpellCheckerLegacyConfiguration.ExclusionExpressions")]
[assembly: SuppressMessage("Design", "CA1002:Do not expose generic lists", Justification = "<Pending>", Scope = "member", Target = "~P:VisualStudio.SpellChecker.Common.Configuration.Legacy.SpellCheckerLegacyConfiguration.AdditionalDictionaryFolders")]
[assembly: SuppressMessage("Design", "CA1002:Do not expose generic lists", Justification = "<Pending>", Scope = "member", Target = "~P:VisualStudio.SpellChecker.Common.Configuration.Legacy.SpellCheckerLegacyConfiguration.VisualStudioIdExclusions")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:VisualStudio.SpellChecker.Common.Configuration.Legacy.SpellCheckerLegacyConfiguration.#ctor(System.String)")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:VisualStudio.SpellChecker.Common.Configuration.Legacy.SpellCheckerLegacyConfiguration.Load")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:VisualStudio.SpellChecker.Common.Configuration.Legacy.SpellCheckerLegacyConfiguration.DefaultValueFor(System.String)~System.Object")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:VisualStudio.SpellChecker.Common.Configuration.Legacy.SpellCheckerLegacyConfiguration.ToRegexes(System.String,System.String)~System.Collections.Generic.IEnumerable{System.Text.RegularExpressions.Regex}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:VisualStudio.SpellChecker.Common.EditorConfig.SectionLine.IsMatchForFile(System.String)~System.Boolean")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:VisualStudio.SpellChecker.Common.Configuration.SpellCheckerDictionary.AvailableDictionaries(System.Collections.Generic.IEnumerable{System.String})~System.Collections.Generic.IDictionary{System.String,VisualStudio.SpellChecker.Common.Configuration.SpellCheckerDictionary}")]
[assembly: SuppressMessage("Performance", "CA1810:Initialize reference type static fields inline", Justification = "<Pending>", Scope = "member", Target = "~M:VisualStudio.SpellChecker.Common.Configuration.SpellCheckerConfiguration.#cctor")]
[assembly: SuppressMessage("Naming", "CA1711:Identifiers should not have incorrect suffix", Justification = "<Pending>", Scope = "type", Target = "~T:VisualStudio.SpellChecker.Common.SpellingDictionary")]
[assembly: SuppressMessage("Naming", "CA1711:Identifiers should not have incorrect suffix", Justification = "<Pending>", Scope = "type", Target = "~T:VisualStudio.SpellChecker.Common.GlobalDictionary")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:VisualStudio.SpellChecker.Common.GlobalDictionary.IsSpelledCorrectly(System.String)~System.Boolean")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:VisualStudio.SpellChecker.Common.GlobalDictionary.SuggestCorrections(System.String)~System.Collections.Generic.IEnumerable{VisualStudio.SpellChecker.Common.SpellingSuggestion}")]
[assembly: SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "<Pending>", Scope = "member", Target = "~M:VisualStudio.SpellChecker.Common.GlobalDictionary.InitializeDictionary(System.Collections.Generic.IEnumerable{System.String})")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:VisualStudio.SpellChecker.Common.GlobalDictionary.CreateGlobalDictionary(System.Globalization.CultureInfo,System.Collections.Generic.IEnumerable{System.String},System.Collections.Generic.IEnumerable{System.String},System.Boolean)~VisualStudio.SpellChecker.Common.GlobalDictionary")]
[assembly: SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "<Pending>", Scope = "member", Target = "~M:VisualStudio.SpellChecker.Common.GlobalDictionary.LoadUserDictionaryFile(System.Globalization.CultureInfo)")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:VisualStudio.SpellChecker.Common.GlobalDictionary.LoadUserDictionaryFile")]
[assembly: SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "<Pending>", Scope = "member", Target = "~M:VisualStudio.SpellChecker.Common.GlobalDictionary.LoadUserDictionaryFile")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:VisualStudio.SpellChecker.Common.GlobalDictionary.AddSuggestion(System.String)")]
[assembly: SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "<Pending>", Scope = "member", Target = "~M:VisualStudio.SpellChecker.Common.GlobalDictionary.RemoveWord(System.Globalization.CultureInfo,System.String)")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:VisualStudio.SpellChecker.Common.GlobalDictionary.AddSuggestions")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:VisualStudio.SpellChecker.Common.GlobalDictionary.RemoveWord(System.String)")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "<Pending>", Scope = "member", Target = "~M:VisualStudio.SpellChecker.Common.Configuration.Legacy.SpellCheckerLegacyConfiguration.ConvertFromLegacyConfiguration~System.ValueTuple{System.Collections.Generic.IEnumerable{System.ValueTuple{System.String,System.String}},System.Collections.Generic.IEnumerable{System.String}}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:VisualStudio.SpellChecker.Common.GlobalDictionary.IsSpelledCorrectlyIgnoreCase(System.String)~System.Boolean")]
