<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<AssemblyName>VisualStudio.SpellChecker.Common</AssemblyName>
		<RootNamespace>VisualStudio.SpellChecker.Common</RootNamespace>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<Title>Spell Check My Code Common Code</Title>
		<AssemblyTitle>Spell Check My Code Common Code</AssemblyTitle>
		<Description>This assembly contains interfaces and other supporting classes used to implement a spell checker for Visual Studio</Description>
		<PlatformTarget>AnyCPU</PlatformTarget>
		<Configurations>Debug;Release</Configurations>
		<NoWarn>NU1701,NU1702</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="..\VSSpellCheckerDefinitions\Properties\AssemblyInfoShared.cs" Link="Properties\AssemblyInfoShared.cs" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Dictionaries\de_DE.aff" />
	  <EmbeddedResource Include="Dictionaries\de_DE.dic" />
	  <EmbeddedResource Include="Dictionaries\en_AU.aff" />
	  <EmbeddedResource Include="Dictionaries\en_AU.dic" />
	  <EmbeddedResource Include="Dictionaries\en_CA.aff" />
	  <EmbeddedResource Include="Dictionaries\en_CA.dic" />
	  <EmbeddedResource Include="Dictionaries\en_GB.aff" />
	  <EmbeddedResource Include="Dictionaries\en_GB.dic" />
	  <EmbeddedResource Include="Dictionaries\en_NZ.aff" />
	  <EmbeddedResource Include="Dictionaries\en_NZ.dic" />
	  <EmbeddedResource Include="Dictionaries\en_US.aff" />
	  <EmbeddedResource Include="Dictionaries\en_US.dic" />
	  <EmbeddedResource Include="Dictionaries\en_ZA.aff" />
	  <EmbeddedResource Include="Dictionaries\en_ZA.dic" />
	  <EmbeddedResource Include="Dictionaries\es_ES.aff" />
	  <EmbeddedResource Include="Dictionaries\es_ES.dic" />
	  <EmbeddedResource Include="Dictionaries\fr_FR.aff" />
	  <EmbeddedResource Include="Dictionaries\fr_FR.dic" />
	  <EmbeddedResource Include="Dictionaries\it_IT.aff" />
	  <EmbeddedResource Include="Dictionaries\it_IT.dic" />
	  <EmbeddedResource Include="Dictionaries\LGPL-License.txt" />
	  <EmbeddedResource Include="Dictionaries\pt_BR.aff" />
	  <EmbeddedResource Include="Dictionaries\pt_BR.dic" />
	  <EmbeddedResource Include="Dictionaries\pt_PT.aff" />
	  <EmbeddedResource Include="Dictionaries\pt_PT.dic" />
	  <EmbeddedResource Include="Dictionaries\README_de_DE.txt" />
	  <EmbeddedResource Include="Dictionaries\README_en_AU.txt" />
	  <EmbeddedResource Include="Dictionaries\README_en_CA.txt" />
	  <EmbeddedResource Include="Dictionaries\README_en_GB.txt" />
	  <EmbeddedResource Include="Dictionaries\README_en_NZ.txt" />
	  <EmbeddedResource Include="Dictionaries\README_en_US.txt" />
	  <EmbeddedResource Include="Dictionaries\README_en_ZA.txt" />
	  <EmbeddedResource Include="Dictionaries\README_es_ES.txt" />
	  <EmbeddedResource Include="Dictionaries\README_fr_FR.txt" />
	  <EmbeddedResource Include="Dictionaries\README_it_IT.txt" />
	  <EmbeddedResource Include="Dictionaries\README_pt_BR.TXT" />
	  <EmbeddedResource Include="Dictionaries\README_pt_PT.txt" />
	  <EmbeddedResource Include="Dictionaries\README_ru_RU.txt" />
	  <EmbeddedResource Include="Dictionaries\README_sl_SI.txt" />
	  <EmbeddedResource Include="Dictionaries\README_sr.txt" />
	  <EmbeddedResource Include="Dictionaries\ru_RU.aff" />
	  <EmbeddedResource Include="Dictionaries\ru_RU.dic" />
	  <EmbeddedResource Include="Dictionaries\sl_SI.aff" />
	  <EmbeddedResource Include="Dictionaries\sl_SI.dic" />
	  <EmbeddedResource Include="Dictionaries\sr-Latn.aff" />
	  <EmbeddedResource Include="Dictionaries\sr-Latn.dic" />
	  <EmbeddedResource Include="Dictionaries\sr.aff" />
	  <EmbeddedResource Include="Dictionaries\sr.dic" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="WeCantSpell.Hunspell" />
		<ProjectReference Include="..\VSSpellCheckerDefinitions\VSSpellCheckerDefinitions.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

</Project>
